server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway-${COMPUTERNAME}
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
zuul: 
   #隐藏真实服务名称,使得  http://GATEWAY:GATEWAY_PORT/想要访问的Eureka服务id的小写/**  的方式无法访问, 隐藏所有的真实服务名称,使用 "*"
   ignored-services: microservicecloud-dept 
   prefix: /lang #添加服务的公共前缀
   routes:
      langdept: 
         serviceId: microservicecloud-dept
         path: /mydept/** 

 
info:
  app.name: lang-microcloud
  company.name: www.lang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

